### ISSUE TITLE
TASK 4

### ISSUE THREAD

**Issue by Justarone** [maxim218/JavaScript-Tasks-IU#1]
Задание №3. Генерировать HTML-страничку надо вручную или с помощью Handlebars/pug/ejs?

**Comment by maxim218** [comment]
Вручную. Шаблонизаторы пока не используем.

**Comment by Justarone** [comment]
Хорошо, вопрос исчерпан

**Comment by akenoq** [comment]
> Вручную. Шаблонизаторы пока не используем.

Дополню ответ, в решении можно использовать шаблонные строки JS https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/template_strings
